name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ui

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js at specific version
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run test
